"""added is cool to authors

Revision ID: 84e267087b5b
Revises: ffe6e4bd99a8
Create Date: 2026-06-23 23:21:01.781811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e267087b5b'
down_revision: Union[str, Sequence[str], None] = 'ffe6e4bd99a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_cool', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_cool')
    # ### end Alembic commands ###
